baseURL = "https://sethdelorme.com"
title = "Seth Delorme"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, Seth Delorme"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    title = "About"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -90

# Configuration Features
[params]
  description = "Your meta description"      # Your meta description of the site
  header_title = "Seth Delorme"                 # Your header title
  header_subtitle = "Dev | Educator >> Ann Arbor, MI" # Your header subtitle
  home_image = "/images/headshot.jpg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
      backgroundColor = "#f8f9fa"
      homeImageBorderColor = "#ffffff"
      fontFamilyBase = "Helvetica Neue"
      fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/sdelorme"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/seth-delorme/"
  [[params.social]]
    fa_icon = "fas fa-envelope fa-1x"
    href = "mailto:delorme.s.m@gmail.com"
