name: Gatsby Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Clear Gatsby Cache
        run: npm run clean

      - name: Deploy
        run: npm run deploy:ci
